/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devices the product knows about (available and planned) */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/songs/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search songs (canonical IDs from MusicBrainz) */
        get: operations["searchSongs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a presigned URL for a direct-to-storage upload */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/{uploadId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signal that the file was uploaded; starts server-side probing */
        post: operations["completeUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/uploads/{uploadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get upload status */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Curated example generations (public, read-only)
         * @description Examples are finished generations curated by the team. Their prose (headline, summary,
         *     explanations) exists per locale, so `generation_id` points to the generation produced in
         *     the requested `locale`. They never appear in `GET /v1/generations` and reject mutations
         *     (cancel, retry, feedback) with `409 conflict`.
         */
        get: operations["listExamples"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/examples/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One example; its generation, tone profile and preset are read with the usual endpoints */
        get: operations["getExample"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my generations */
        get: operations["listGenerations"];
        put?: never;
        /** Start a tone generation (asynchronous) */
        post: operations["createGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a generation (poll this) */
        get: operations["getGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a running generation */
        post: operations["cancelGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/generations/{generationId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry a failed generation from its last successful step */
        post: operations["retryGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tone-profiles/{toneProfileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a tone profile */
        get: operations["getToneProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets/{presetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a preset and its versions */
        get: operations["getPreset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets/{presetId}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one preset version */
        get: operations["getPresetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets/{presetId}/versions/{version}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Device file for this version (GP-180 `.prst`, 1128 bytes) */
        get: operations["downloadPresetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/presets/{presetId}/versions/{version}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rate a preset version */
        post: operations["sendFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Locale: "en" | "es";
        /**
         * @description Stable machine-readable error/warning code. Clients localize the message.
         * @enum {string}
         */
        ErrorCode: "validation_error" | "unauthorized" | "not_found" | "conflict" | "rate_limited" | "unsupported_format" | "invalid_audio" | "audio_too_short" | "audio_too_long" | "file_too_large" | "no_guitar_detected" | "multiple_guitars" | "low_quality_audio" | "song_not_found" | "research_unavailable" | "ai_unavailable" | "mapping_failed" | "preset_generation_failed" | "unsupported_device" | "job_timeout" | "internal";
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            code: components["schemas"]["ErrorCode"];
            detail?: string;
            retryable: boolean;
            /** @description Optional machine hint for the client (e.g. `choose_other_section`). */
            hint?: string;
            /** @description Field-level validation errors. */
            errors?: {
                field: string;
                code: string;
            }[];
        };
        Device: {
            /** @example valeton_gp180 */
            key: string;
            vendor: string;
            name: string;
            /** @enum {string} */
            status: "available" | "planned";
            /** @description How presets reach the device. */
            delivery: ("preset_file" | "dial_in_sheet")[];
            /** @example .prst */
            file_extension?: string | null;
            /** @example Valeton Suite */
            import_via?: string | null;
        };
        SongCandidate: {
            /** @description Canonical recording ID (MusicBrainz MBID in production) */
            id: string;
            title: string;
            artist: string;
            year?: number | null;
            duration_s?: number | null;
        };
        UploadCreate: {
            /** @enum {string} */
            purpose: "reference" | "recording";
            filename: string;
            /** @enum {string} */
            content_type: "audio/wav" | "audio/x-wav" | "audio/flac" | "audio/mpeg" | "audio/mp4" | "audio/aac" | "audio/ogg";
            size_bytes: number;
        };
        UploadTicket: {
            upload_id: string;
            /** @description Presigned URL; PUT the raw bytes */
            put_url: string;
            headers: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
            max_bytes: number;
        };
        Upload: {
            id: string;
            /** @enum {string} */
            purpose: "reference" | "recording";
            /** @enum {string} */
            status: "awaiting_upload" | "probing" | "ready" | "rejected";
            duration_s?: number | null;
            sample_rate?: number | null;
            channels?: number | null;
            error?: components["schemas"]["Problem"] | null;
        };
        TimeWindow: {
            start_s: number;
            /** @description end_s - start_s must be between 5 and 90 seconds */
            end_s: number;
        };
        /** @enum {string} */
        PickupConfig: "sss" | "hss" | "hh" | "ss" | "p90" | "single_humbucker" | "other";
        /** @enum {string} */
        PickupPosition: "neck" | "middle" | "bridge" | "neck_middle" | "middle_bridge" | "neck_bridge";
        /** @enum {string} */
        Tuning: "standard" | "eb_standard" | "drop_d" | "d_standard" | "drop_c" | "open_g" | "open_d" | "other";
        GuitarInput: {
            pickup_config: components["schemas"]["PickupConfig"];
            pickup_position: components["schemas"]["PickupPosition"];
            tuning: components["schemas"]["Tuning"];
        };
        /** @description At least one of `song_id` or `reference` is required. */
        GenerationCreate: {
            song_id?: string | null;
            reference?: {
                upload_id: string;
                window: components["schemas"]["TimeWindow"];
            } | null;
            /** @enum {string|null} */
            section_hint?: "intro" | "verse" | "chorus" | "riff" | "solo" | "clean_part" | null;
            device_key: string;
            guitar: components["schemas"]["GuitarInput"];
            locale: components["schemas"]["Locale"];
        };
        /** @enum {string} */
        GenerationStatus: "queued" | "running" | "ready" | "failed" | "cancelled";
        /**
         * @description Pipeline steps in execution order.
         * @enum {string}
         */
        StepKey: "resolve_song" | "analyze_audio" | "research_gear" | "draft_intent" | "map_to_device" | "validate_patch" | "build_preset";
        /** @enum {string} */
        StepStatus: "pending" | "running" | "done" | "skipped" | "failed";
        /** @description Structured facts produced by a step. The client renders and localizes them. */
        StepSummary: {
            /** @constant */
            kind: "song";
            title: string;
            artist: string;
            year?: number | null;
        } | {
            /** @constant */
            kind: "audio";
            analyzed_s: number;
            /** @enum {string} */
            separation: "none" | "stem_model";
            guitar_dominance: number;
            gain_class: components["schemas"]["GainClassEstimate"];
        } | {
            /** @constant */
            kind: "research";
            sources_read: number;
            claims_kept: number;
            /** @description Claims removed because their quote could not be verified */
            claims_dropped: number;
        } | {
            /** @constant */
            kind: "intent";
            blocks: number;
            amp_archetype: components["schemas"]["Archetype"];
        } | {
            /** @constant */
            kind: "mapping";
            candidates_evaluated: number;
            /** @description Mean absolute LTAS error vs. measured target, when a measured target exists. */
            spectral_error_db: number | null;
        } | {
            /** @constant */
            kind: "validation";
            checks_passed: number;
            checks_total: number;
        } | {
            /** @constant */
            kind: "preset";
            file_bytes: number | null;
        };
        Step: {
            key: components["schemas"]["StepKey"];
            status: components["schemas"]["StepStatus"];
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            summary?: components["schemas"]["StepSummary"] | null;
        };
        Warning: {
            code: components["schemas"]["ErrorCode"];
            step?: components["schemas"]["StepKey"];
        };
        Generation: {
            id: string;
            status: components["schemas"]["GenerationStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            input: {
                song?: components["schemas"]["SongCandidate"] | null;
                reference_window?: components["schemas"]["TimeWindow"] | null;
                device_key: string;
                guitar: components["schemas"]["GuitarInput"];
                locale: components["schemas"]["Locale"];
            };
            steps: components["schemas"]["Step"][];
            /** @description Typical total duration measured on recent generations of the same mode. */
            estimate: {
                p50_s: number;
                p90_s: number;
            };
            /** @description Suggested delay before polling again */
            poll_after_ms: number;
            warnings: components["schemas"]["Warning"][];
            result?: {
                tone_profile_id: string;
                preset_id: string;
                preset_version: number;
            } | null;
            error?: components["schemas"]["Problem"] | null;
        };
        GenerationListItem: {
            id: string;
            status: components["schemas"]["GenerationStatus"];
            /** Format: date-time */
            created_at: string;
            device_key: string;
            song?: components["schemas"]["SongCandidate"] | null;
            has_reference_audio?: boolean;
            preset_name?: string | null;
        };
        ExampleSummary: {
            /** @example northern-lights */
            slug: string;
            /** @description Ready generation for this example in `locale` (read-only). */
            generation_id: string;
            locale: components["schemas"]["Locale"];
            song: components["schemas"]["SongCandidate"];
            device_key: string;
            has_reference_audio: boolean;
            gain_class: components["schemas"]["GainClass"] | null;
            /** @description Overall tone-profile confidence */
            confidence: number;
            /** @description One-line description of the tone, in `locale` */
            headline: string;
            /** @description Warning codes of the generation, so the list can flag degraded results. */
            warnings: components["schemas"]["ErrorCode"][];
        };
        /** @enum {string} */
        EvidenceLevel: "confirmed" | "reported" | "likely" | "inferred" | "unknown";
        /** @enum {string} */
        Role: "gate" | "compressor" | "boost" | "drive" | "fuzz" | "pitch" | "wah" | "amp" | "cab" | "eq" | "modulation" | "delay" | "reverb" | "volume";
        /**
         * @description Controlled vocabulary; see docs/architecture/tone-representation.md.
         * @enum {string}
         */
        Archetype: "fender_tweed" | "fender_blackface_clean" | "vox_ac_topboost" | "british_plexi" | "british_high_gain" | "american_high_gain_modern" | "dumble_style" | "boutique_edge" | "jazz_solid_state_clean" | "acoustic_sim" | "ts_style_boost" | "klon_style" | "rat_style_distortion" | "muff_style_fuzz" | "fuzz_face_style" | "octave_fuzz" | "clean_boost" | "compressor" | "noise_gate" | "open_back_1x12" | "open_back_2x12" | "closed_back_4x12" | "room" | "plate" | "spring" | "hall" | "shimmer" | "digital_delay" | "analog_delay" | "tape_delay" | "dotted_eighth_delay" | "chorus" | "phaser" | "flanger" | "uni_vibe" | "tremolo" | "rotary";
        /** @enum {string} */
        GainClass: "clean" | "edge_of_breakup" | "crunch" | "high_gain" | "fuzz";
        GainClassEstimate: {
            value: components["schemas"]["GainClass"];
            p: number;
        };
        Source: {
            url: string;
            publisher: string;
            title: string;
            quote_excerpt?: string | null;
            /** Format: date-time */
            retrieved_at: string;
        };
        Claim: {
            id: string;
            role: components["schemas"]["Role"];
            /** @description Gear name as stated by the sources */
            item: string;
            /** @description Localized sentence */
            statement: string;
            /** @enum {string} */
            specificity: "this_recording" | "artist_general";
            evidence_level: components["schemas"]["EvidenceLevel"];
            sources: components["schemas"]["Source"][];
        };
        /** @description Long-term average spectrum, loudness-normalized, 1/3-octave bands. */
        Spectrum: {
            bands_hz: number[];
            db: number[];
        };
        AudioEvidence: {
            window: components["schemas"]["TimeWindow"];
            analyzed_s: number;
            /** @enum {string} */
            separation: "none" | "stem_model";
            guitar_dominance: number;
            ltas: components["schemas"]["Spectrum"];
            gain_class: components["schemas"]["GainClassEstimate"];
            ambience: {
                /** @enum {string} */
                reverb: "none" | "low" | "medium" | "high";
                delay?: {
                    time_ms?: number;
                    /** @enum {string|null} */
                    subdivision?: "quarter" | "dotted_eighth" | "eighth" | null;
                } | null;
                modulation?: {
                    /** @enum {string} */
                    kind?: "chorus" | "phaser" | "flanger" | "tremolo" | "vibrato";
                    rate_hz?: number | null;
                } | null;
            };
        };
        PerceptualTarget: {
            value: number;
            confidence: number;
            /** @enum {string} */
            basis: "measured" | "research" | "inferred";
        };
        IntentBlock: {
            id: string;
            role: components["schemas"]["Role"];
            archetype: components["schemas"]["Archetype"];
            enabled: boolean;
            confidence: number;
            evidence_level: components["schemas"]["EvidenceLevel"];
            alternatives: components["schemas"]["Archetype"][];
            claim_ids?: string[];
        };
        /** @description User-facing Tone Profile = ToneEvidence + ToneIntent (device-independent). */
        ToneProfile: {
            id: string;
            generation_id: string;
            locale: components["schemas"]["Locale"];
            /** @description Localized one-paragraph description */
            summary: string;
            confidence: number;
            evidence: {
                claims: components["schemas"]["Claim"][];
                audio?: components["schemas"]["AudioEvidence"] | null;
            };
            intent: {
                chain: components["schemas"]["IntentBlock"][];
                targets: {
                    saturation: components["schemas"]["PerceptualTarget"];
                    low_end: components["schemas"]["PerceptualTarget"];
                    mid_emphasis: components["schemas"]["PerceptualTarget"];
                    brightness: components["schemas"]["PerceptualTarget"];
                    tightness: components["schemas"]["PerceptualTarget"];
                    compression: components["schemas"]["PerceptualTarget"];
                    ambience: components["schemas"]["PerceptualTarget"];
                };
            };
        };
        DeviceParam: {
            key: string;
            /** @description Label as printed on the device (not translated) */
            label: string;
            value: number;
            /** @enum {string} */
            unit: "knob" | "db" | "hz" | "ms" | "enum" | "bool";
            min: number;
            max: number;
            /** @description Labels for enum units, indexed by value. */
            options?: string[];
        };
        DeviceBlock: {
            /**
             * @example NR
             * @example PRE
             * @example WAH
             * @example DST
             * @example NS
             * @example AMP
             * @example CAB
             * @example EQ
             * @example MOD
             * @example DLY
             * @example RVB
             * @example VOL
             */
            slot: string;
            enabled: boolean;
            model: {
                key: string;
                /** @description Model label shown on the device */
                name: string;
                based_on?: string | null;
            };
            params: components["schemas"]["DeviceParam"][];
            intent_block_id?: string | null;
            confidence: number;
            alternatives: {
                model_key: string;
                name: string;
            }[];
        };
        Preset: {
            id: string;
            device_key: string;
            title: string;
            current_version: number;
            versions: {
                version: number;
                /** Format: date-time */
                created_at: string;
                /** @enum {string} */
                created_by: "generator" | "user_edit" | "match";
            }[];
        };
        PresetVersion: {
            preset_id: string;
            version: number;
            device_key: string;
            catalog_version: string;
            name: string;
            patch_volume: number;
            bpm?: number | null;
            /** @description Blocks in signal order. */
            chain: components["schemas"]["DeviceBlock"][];
            /** @description Localized explanation of the mapping */
            explanation: string;
            validation: {
                ok: boolean;
                checks: {
                    /** @enum {string} */
                    code: "catalog_models" | "parameter_ranges" | "chain_order" | "engine_tags" | "output_level";
                    ok: boolean;
                }[];
            };
            download: {
                available: boolean;
                filename?: string | null;
                /** @enum {string|null} */
                reason?: "demo_mode" | "validation_failed" | "format_unverified" | null;
            };
        };
        FeedbackCreate: {
            usefulness: number;
            closeness?: number | null;
            tags?: ("too_much_gain" | "too_little_gain" | "too_bright" | "too_dark" | "too_boomy" | "too_thin" | "wrong_effects" | "too_much_ambience" | "great_starting_point")[];
            comment?: string | null;
        };
    };
    responses: {
        /** @description Error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        UploadId: string;
        GenerationId: string;
        PresetId: string;
        /** @description Locale of the prose to return; falls back to `en`. */
        LocaleQuery: components["schemas"]["Locale"];
        Version: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Device"][];
                    };
                };
            };
            429: components["responses"]["Problem"];
        };
    };
    searchSongs: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SongCandidate"][];
                    };
                };
            };
            400: components["responses"]["Problem"];
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadCreate"];
            };
        };
        responses: {
            /** @description Upload ticket */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            400: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    completeUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probing started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uploadId: components["parameters"]["UploadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Upload"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listExamples: {
        parameters: {
            query?: {
                /** @description Locale of the prose to return; falls back to `en`. */
                locale?: components["parameters"]["LocaleQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ExampleSummary"][];
                    };
                };
            };
            429: components["responses"]["Problem"];
        };
    };
    getExample: {
        parameters: {
            query?: {
                /** @description Locale of the prose to return; falls back to `en`. */
                locale?: components["parameters"]["LocaleQuery"];
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExampleSummary"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listGenerations: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["GenerationListItem"][];
                        next_cursor: string | null;
                    };
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationCreate"];
            };
        };
        responses: {
            /** @description Accepted; poll the generation */
            202: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            400: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    cancelGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    retryGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: components["parameters"]["GenerationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrying */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Generation"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    getToneProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                toneProfileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToneProfile"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: components["parameters"]["PresetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preset"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getPresetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: components["parameters"]["PresetId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetVersion"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    downloadPresetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: components["parameters"]["PresetId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description File not available for this version (see `download.reason`) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    sendFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                presetId: components["parameters"]["PresetId"];
                version: components["parameters"]["Version"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
}
